### ISSUE TITLE
KNIP Java Snippet

### ISSUE THREAD

**Issue by kmader** [knime-ip/knip#114] opened 2015-03-29 21:18 UTC
It would be brilliant, if you could write and compile ImageJ2 plugins / ops within KNIME using something like the Java Snippet in the standard tools. This would tremendously speed up development for new ImageJ plugins and make it much easier to include slightly more complicated logic as part of workflows.

**Comment by dietzc** [comment] 2015-03-30 03:33
@Squareys is working in exactly this. @Squareys can you comment on the status and plans?

**Comment by Squareys** [comment] 2015-03-30 09:03
Our current goal is the integration of Scijava Command (and derived) Java Code via a dedicated Node, of course with support for images. You will be able to choose between row-to-row and row-to-many rows execution, the latter (at least for current plans) will require special code (i.e. the use of a KNIMEDataTableService). The node dialog will automatically generate the UI for unresolved inputs and will provide means for mapping certain table columns to command inputs.

Currently we can edit and execute commands and previously were able to match columns to inputs as well as generate the UI for unresolved inputs, but had some regression lately due to some refactoring I am currently undertaking.

In the more distant future we also hope to have a node which can hold and manage a compiled Command class file. But the scripting node currently has a higher priority.

**Comment by dietzc** [comment] 2015-10-27 08:50
closed. will be released independently from KNIP Core

**Closed by dietzc** 2015-10-27 08:50 UTC
Labels: newnode
