### ISSUE TITLE
Normalize images for Thumbnails?

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#396] opened 2016-09-13 09:46 UTC
The fact that our thumbnails are not normalized confuses users [for example here](https://tech.knime.org/forum/knime-image-processing/problem-with-image-writer-node), because the result of node operations seems to be a black image. We could  normalize the thumbnails, to prevent this.

**Comment by imagejan** [comment] 2016-09-13 09:49
See also https://github.com/knime-ip/knip/issues/359

**Comment by dietzc** [comment] 2016-09-13 15:22
black or grey image @gab1one. We actually can easily enable normalization for all thumbnails. @hornm what do you think? Anyway, duplicate of #359.

**Closed by dietzc** 2016-09-13 15:22 UTC
Labels: question
