### ISSUE TITLE
Feature Nodes: Possible faulty calculation of ferets diameter

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#329] opened 2016-04-07 18:06 UTC
see: https://tech.knime.org/forum/knime-image-processing/feature-calculator-ferrets-diameter-vs-major-axis#comment-42737

**Comment by Luuklag** [comment] 2016-04-11 08:54
I think the differences are because of different methods of calculation. I looked somewhat deeper into it, trying to understand this. The Major and Minor axis are the axis of a fitted ellipsoid to the ROI. Whilst the Ferets Diameter is calculated by stepwise determining the length of two points along the border.

**Comment by Luuklag** [comment] 2016-04-11 09:25
I only couldn't find the exact code where these things calculated in Github.

**Comment by dietzc** [comment] 2016-04-11 09:27
https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultFeret.java
https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultMajorAxis.java
https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultMinorAxis.java
https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/geom/geom2d/DefaultMinorMajorAxis.java

**Comment by Luuklag** [comment] 2016-04-11 09:36
It is as I thought. MinorMajorAxis fits an ellipsoid, and determines the major and minor axis of that. Whilst Feret calculates the length between two points on the border for points using a certain stepsize to go over the border. And if correct the line should always fross the centre of mass of the ROI. So here the differences originate. So it's probably not a bug but just two ways of calculating something.

**Comment by tibuch** [comment] 2016-10-11 13:27
This PR https://github.com/imagej/imagej-ops/pull/454 should solve the issue.

**Comment by tibuch** [comment] 2016-11-21 11:08
PR merged.

**Closed by tibuch** 2016-11-21 11:08 UTC
