### ISSUE TITLE
Set Image Metadata: Offset setting translates the image

### ISSUE THREAD

**Issue by HedgehogCode** [knime-ip/knip#484] opened 2017-10-23 07:42 UTC
The 'Set Image Metadata' node translates the image by the given offset instead of using the offset as the new min values.
This behavior is unexpected because the node is not a translate node but is called '__Set__ Image Metadata'. Additionally, the offset is not listed in the node description.

The translate happens in [this line](https://github.com/knime-ip/knip/blob/90eb4e8bd5c92db585788d3050057dd5919520fa/org.knime.knip.base/src/org/knime/knip/base/nodes/metadata/setimgmetadata/SetImgMetadataNodeModel.java#L264).

**Comment by tibuch** [comment] 2017-10-23 07:45
Thanks @HedgehogCode for opening this issue!

**Comment by imagejan** [comment] 2017-10-23 07:47
Duplicate of https://github.com/knime-ip/knip/issues/467

**Comment by tibuch** [comment] 2017-10-23 07:51
Oh! That is unfortunate :smile: 

Then we can close this issue. Thanks @imagejan for pointing it out.

**Closed by tibuch** 2017-10-23 07:51 UTC
Labels: bug
