### ISSUE TITLE
Image Reader: Some .tif images do not have Source set

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#423] opened 2016-11-17 10:39 UTC
Could not test with the very latest KNIP yet, but this should be easy to verify. Left the signal empty intentionally. The example.zip contains such a tiff file.
[example.zip](https://github.com/knime-ip/knip/files/597081/example.zip)

**Comment by dietzc** [comment] 2016-11-17 12:24
the error is in the `ImageReader` you say?

**Comment by maierl** [comment] 2016-11-17 12:58
Yes.

**Comment by dietzc** [comment] 2016-11-17 12:59
Did you add the particular tiff files to the workflow?

**Comment by maierl** [comment] 2016-11-17 13:03
The .zip contains only the tiff file.

- Lorenz [mobile]


Am 17.11.2016 um 13:59 schrieb Christian Dietz <notifications@github.com<mailto:notifications@github.com>>:


Did you add the particular tiff files to the workflow?

**Comment by gab1one** [comment] 2016-11-30 15:23
I could not reproduce this bug, on linux with the latest knip-nightly the example image has the source property set: 
![imagereadersourcebug](https://cloud.githubusercontent.com/assets/1938154/20758039/d5f518d2-b718-11e6-8868-e692bf7b37fa.png)

If the error still occurs please send me a workflow with the runtime data (uncheck the "Exclude data from export" option), maybe that gives us insight into this issue.

**Comment by gab1one** [comment] 2016-12-13 10:55
Could not reproduce the issue, closing this for now.

**Closed by gab1one** 2016-12-13 10:55 UTC
Labels: bug

**Comment by beschu** [comment] 2017-01-18 13:10
Maybe related to some error I encounter in a Workflow i created for another issue:

See issue: #160

"I created a workflow (named: multi-channel-images-issue160) and placed it on merkur. It checks for this bug and some other stuff i encountered:

- Sometimes it appears that a source does not get set."
