### ISSUE TITLE
Image Reader: Metainfo only

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#43] opened 2014-09-04 13:57 UTC
The image reader, or a custom new node, should be able to output only the meta information of an image without reading all of it.

An alternative solution and / or side-project could be removing the need for an input image at the ImageJ Macro Node.

**Comment by maierl** [comment] 2015-01-08 12:42
just to clarify a bit, I'd be especially interested in the "original metadata", not only the OME-XML metadata.

**Comment by dietzc** [comment] 2015-03-03 12:27
duplicate of https://github.com/knime-ip/knip/issues/96

**Closed by dietzc** 2015-03-03 12:27 UTC
Labels: enhancement, new-imagereader
