### ISSUE TITLE
Aggregation method Merge only supports 2D to 3D, not 3D to 4D

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#419] opened 2016-11-09 14:40 UTC
When using the _GroupBy_ node with aggregation method "Merge Image", I can choose the name of the newly created dimension, but if my input has e.g. X,Y,Z, only the first Z plane will be considered for the merge operation. I tried with different combinations (input X,Y,Z, new Channel; input X,Y,Channel, new Z; etc.)

The issue is presumably in [`ImgMergeOperator.java`](https://github.com/knime-ip/knip/blob/f893245/org.knime.knip.base/src/org/knime/knip/base/data/aggregation/ImgMergeOperator.java#L565-L570).

As a workaround, you can use the _Pivoting_ and _Merger_ nodes.

**Comment by maierl** [comment] 2016-11-11 12:41
Thanks for confirming that problem. It is the same as #175, isn't it?

**Comment by hornm** [comment] 2016-11-21 15:14
Another workaround could probably be using a combination of _Dimension Extener_, _Java Snippet_ and _Set Image Metadata_ nodes in order to the the individual image offsets that can be used to finally compose them to a new image via the _Image Compose_ aggregation method (GroupBy).

That doesn't mean we shouldn't support nD in the merge operator ;)

**Comment by hornm** [comment] 2016-11-22 08:35
Merge Image aggregation operator now supports nD images (however, it's most efficient in the 2D case).

Testflow updated:
knime://knime.mountpoint/Testflows/trunk/ImageProcessing/knip/KNIME_testing_GroupBy

**Comment by gudlap** [comment] 2016-12-08 21:09
Sorry for (re)-opening a closed ticket. But looks like the above fix (#419) broke the ability to merge 2D images in a column 2D-t image.  At least that my naive thinking without actually looking into the code.

Using the "Merge" operation in GroupBy Node from latest nightly builds (for KNIME 3.2.1) results in Merged image with axes XYT but T index is always 1. I get the same results also for KNIME 3.3.0 with KNIP (1.5.3.201612060455 build date).

The Merge operation, however, works as expected in KNIP build date 1.5.3.201611190650.  


Pass/Fails Details:

KNIME 3.3.0 (Win64):  Fails
 KNIME Image Processing	1.5.3.201612060455

KNIME 3.3.0 (Win64):  Fails
KNIME Image Processing	1.5.3.201612040725

KNIME 3.2.1 (Win64):  Fails
KNIME Image Processing	1.5.3.201612040725

KNIME 3.2.1 (Win64):  Works as expected.
KNIME Image Processing	1.5.3.201611190650

**Comment by gudlap** [comment] 2017-03-03 19:59
Hi -

Just wanted to check-in to see if there has been any update on the (potential) bug with creating 2D-T images from the "Merge Image" operation of the GroupBy Node?

Thanks

**Comment by dietzc** [comment] 2017-03-07 22:53
@gudlap we will take care! sorry for the delay.

**Comment by hornm** [comment] 2017-03-14 08:29
Fixed. I introduced a regression with the last bug fix :neutral_face: 
Testflow knime://knime.mountpoint/Testflows/trunk/ImageProcessing/knip/KNIME_testing_GroupBy updated. For a reason the former bugfix wasn't tested with the testflow - either because I didn't upload the updated testflow (although I claimed I did) or it has been overridden with an older version ...

**Closed by hornm** 2017-03-14 08:29 UTC

**Comment by gudlap** [comment] 2017-03-21 13:01
@dietzc and @hornm: Thanks a lot for the fix. I can confirm that issue is resolved in the nightly build. This will help us with moving to KNIME 3.3.x.
