### ISSUE TITLE
Image Reader: Allow output of metadata only

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#96] opened 2015-02-26 13:22 UTC
Add the possibility for the user to select the output of the reader: image, image+metadata, metadata only.

**Comment by maierl** [comment] 2015-02-26 15:37
Btw: There are two levels of metadata: the OME-XML and the “raw” / original metadata, as it is displayed in the preview.

It would be good to get the raw metadata, too.

**Comment by maierl** [comment] 2015-03-03 11:08
this is a duplicate of #43, isn't it?

**Comment by dietzc** [comment] 2015-03-03 14:50
important!

**Closed** 2015-03-19 11:08 UTC
Labels: enhancement

**Comment by maierl** [comment] 2015-03-19 13:21
this update only allows to use only the ome-xml metadata, not the raw metadata, right?

**Comment by dietzc** [comment] 2015-03-19 13:30
OME-Metadata should represent most of the raw meta-data. Are you missing some information in the resulting XML?

**Comment by maierl** [comment] 2015-03-19 13:59
I am thinking of the plate design here (i.e. which row and column was this position). I didn’t see any such information in the OME-XML metadata.

**Comment by dietzc** [comment] 2015-03-19 14:00
Can you provide an example where the meta-data is accessible in FIJI but not in KNIME?

**Comment by maierl** [comment] 2015-03-19 14:54
https://powerfolder.dkfz.de/dl/fiJtvzbFLwTjUtE3QVw6pKRC/AL__W0002__P0001__T0017.czi.czi
E.g. Detector Gain

**Comment by dietzc** [comment] 2015-03-19 14:55
@gab1one can you check/explain why this is not part of the resulting ome-xml?

**Comment by maierl** [comment] 2015-03-19 15:09
@gab1one sorry, I was too quick on that one. I tried to avoid using a 12gb file just to have a file with full plate specifications that can be read by bioformats on its own.

The gain is actually included in the ome-xml, too.

**Comment by maierl** [comment] 2015-03-19 15:26
https://powerfolder.dkfz.de/dl/fiF6P38XAxRz5u1GEMvcr4EX/.zip
Experiment|AcquisitionBlock|TilesSetup|SampleHolder|SingleTileRegionArray|SingleTileRegion|Category|Name #001

**Comment by dietzc** [comment] 2015-03-19 15:36
maybe a more general question @hinerm: Shouldn't (in theory) any metadata be part of the ome-xml metadata (maybe in some tag: <Uncategorized>)?

**Comment by hinerm** [comment] 2015-03-19 16:09
@dietzc so is the problem that you have the dataset mentioned by @maierl with the specified raw metadata tag, and it's not translated into OME-XML? What is the base format of the dataset? (can't unzip it on my mac)

For reference, the [OME-XML schema documentation](http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/ome.html) doesn't specify that metadata.

Basically, any metadata will only be part of the ome-xml metadata if there is something in the reader that explicitly translates the raw metadata to the OME schema.

The dumping tag for raw metadata is in the [Structured Annotations](http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/SA_xsd.html#StructuredAnnotations) XML, if the complete OME-XMLization step is enabled (may be off by default since it can make the resulting XML very large).

**Comment by hinerm** [comment] 2015-03-19 16:12
P.S. the '''actual''' method for full OME-XML generation `setPopulateOriginalMetadata(true)` which would have to be called before `setId` if you're using a Bio-Formats reader.

If you're using SCIFIO it may not be exposed properly, which would be a bug/limitation of the `BioFormatsFormat`...

**Comment by dietzc** [comment] 2015-03-19 16:25
thanks for the clarification @hinerm. So if I understand it correctly, full OME-XML means that any raw-metadata is translated into OME-XML, even if not explicitly specified/supported by the OME-XML Metadata?

@maierl can you help @hinerm with the information about the base format?

**Comment by dietzc** [comment] 2015-03-19 16:26
it's a 7z inside the 7z which contains a czi file.

**Comment by hinerm** [comment] 2015-03-19 16:33
>So if I understand it correctly, full OME-XML means that any raw-metadata is translated into OME-XML

In the sense that "everything gets dumped into the `Structured Annotations` element," yes.

>which contains a czi file

As far as I can tell, the CZI Reader doesn't parse a `category` tag from [SingleTileRegion](https://github.com/openmicroscopy/bioformats/blob/v5.0.7/components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java#L2181-2205). So if you want to populate that tag you will need to `setPopulateOriginalMetadata(true)` and interrogate `Structured Annotations`.

**Comment by gab1one** [comment] 2015-03-19 16:57
We are creating an empty OME-XML Metadata object and using the SCIFIO TranslatorService.translate(..) function to fill it with the metadata from the image. 
[Take a look here:](https://github.com/knime-ip/knip/blob/master/org.knime.knip.io/src/org/knime/knip/io/ScifioImgSource.java#L227-L235).
@hinerm  I am not sure where I can set setPopulateOriginalMetadata(true), can you please elaborate more on that?

**Comment by hinerm** [comment] 2015-03-19 17:18
@gab1one that method is a Bio-Formats method. Since you're using SCIFIO you don't actually need to call it.

Instead, what you need to do is call [SCIFIOConfig.parserSetSaveOriginalMetadata](https://github.com/scifio/scifio/blob/scifio-0.21.1/src/main/java/io/scif/config/SCIFIOConfig.java#L241) on the SCIFIOConfig that's [used to parse your metadata](https://github.com/knime-ip/knip/blob/master/org.knime.knip.io/src/org/knime/knip/io/ScifioImgSource.java#L401).

This will then make [the BioFormats SCIFIO format](https://github.com/scifio/scifio-bf-compat/blob/scifio-bf-compat-1.11.0/src/main/java/io/scif/bf/BioFormatsFormat.java#L421) do the right thing

**Comment by dietzc** [comment] 2015-03-19 17:38
@gab1one we could make this optional, too.

**Comment by gab1one** [comment] 2015-03-19 17:54
Already on it.

**Comment by hinerm** [comment] 2015-03-19 18:28
:octopus:

**Comment by gab1one** [comment] 2015-03-19 18:29
@maierl This option does create farly large xml files, nearly 19k lines with your example (courtesy of the xml format)  but contains all meta data.

**Comment by maierl** [comment] 2015-03-20 11:46
Thanks to all of you for your quick help!
